# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 23:12
from __future__ import unicode_literals

from django.db import migrations


def remove_forum_branding_display_setting(apps, schema_editor):
    Setting = apps.get_model('misago_conf', 'Setting')
    Setting.objects.filter(setting='forum_branding_display').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('misago_core', '0002_basic_settings'),
    ]

    operations = [
        migrations.RunPython(remove_forum_branding_display_setting),
    ]
