# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-26 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("misago_theming", "0002_create_default_theme")]

    operations = [
        migrations.AddField(
            model_name="theme",
            name="author",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="theme",
            name="license",
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
        migrations.AddField(
            model_name="theme",
            name="url",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
