# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-26 22:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("misago_theming", "0004_auto_20181226_2136")]

    operations = [
        migrations.CreateModel(
            name="Css",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("url", models.URLField(blank=True, max_length=255, null=True)),
                (
                    "file",
                    models.ImageField(
                        blank=True, max_length=255, null=True, upload_to=""
                    ),
                ),
                ("size", models.PositiveIntegerField()),
                ("order", models.IntegerField(default=0)),
                ("is_enabled", models.BooleanField(default=True)),
                ("uploaded_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="css",
                        to="misago_theming.Theme",
                    ),
                ),
            ],
            options={"ordering": ["order"]},
        ),
        migrations.CreateModel(
            name="Font",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("file", models.FileField(max_length=255, upload_to="")),
                ("type", models.CharField(max_length=255)),
                ("size", models.PositiveIntegerField()),
                ("uploaded_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fonts",
                        to="misago_theming.Theme",
                    ),
                ),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("file", models.ImageField(max_length=255, upload_to="")),
                ("type", models.CharField(max_length=255)),
                ("width", models.PositiveIntegerField()),
                ("heigh", models.PositiveIntegerField()),
                ("size", models.PositiveIntegerField()),
                ("uploaded_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="images",
                        to="misago_theming.Theme",
                    ),
                ),
            ],
            options={"ordering": ["name"]},
        ),
    ]
