project_name: community-app-web

django_file_storage: storages.backends.s3boto3.S3Boto3Storage
django_staticfile_storage: storages.backends.s3boto3.S3Boto3Storage

service_packages:
  - big_health.services.community_app.service.CommunityApp

access_token_cookie_expiration_seconds: 1000
refresh_token_cookie_expiration_days: 100
