use_remote_dynamic_settings: false

DEBUG: true

secure_cookies: false # Enable if using a proxy like ngrok

django_file_storage: django.core.files.storage.FileSystemStorage
django_staticfile_storage: django.contrib.staticfiles.storage.StaticFilesStorage

db:
  hostname: community-postgres
  name: community
  password: community
  port: 5432
  username: community

email_backend: django.core.mail.backends.console.EmailBackend
enable_risk_words_notifications: false

sleepio_app_url: http://app.sleepio.localhost:8100/sleepio/login/?source=community
