# Generated by Django 4.2.10 on 2025-06-20 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("misago_polls", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            """
            INSERT INTO misago_polls_poll (
                id,
                category_id,
                thread_id,
                starter_id,
                starter_name,
                starter_slug,
                started_at,
                question,
                choices,
                duration,
                max_choices,
                can_change_vote,
                is_public,
                is_closed,
                votes,
                plugin_data
            )
            SELECT
                id,
                category_id,
                thread_id,
                poster_id,
                poster_name,
                poster_slug,
                posted_on,
                question,
                choices::jsonb,
                length,
                allowed_choices,
                allow_revotes,
                is_public,
                'false',
                votes,
                plugin_data::jsonb
            FROM misago_threads_poll;
            """,
            migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            """
            INSERT INTO misago_polls_pollvote (
                id,
                category_id,
                thread_id,
                poll_id,
                voter_id,
                voter_name,
                voter_slug,
                voted_at,
                choice_id
            )
            SELECT
                id,
                category_id,
                thread_id,
                poll_id,
                voter_id,
                voter_name,
                voter_slug,
                voted_on,
                choice_hash
            FROM misago_threads_pollvote;
            """,
            migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            """
            SELECT SETVAL(
                'misago_polls_poll_id_seq',
                (SELECT last_value FROM misago_threads_poll_id_seq)
            );
            """,
            migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            """
            SELECT SETVAL(
                'misago_polls_pollvote_id_seq',
                (SELECT last_value FROM misago_threads_pollvote_id_seq)
            );
            """,
            migrations.RunSQL.noop,
        ),
    ]
