# Generated by Django 4.2.10 on 2025-06-20 22:30

from django.db import migrations


def update_polls_choices(apps, _):
    Poll = apps.get_model("misago_polls", "Poll")

    for poll in Poll.objects.order_by("-id").iterator():
        new_choices = []
        for choice in poll.choices:
            new_choices.append(
                {
                    "id": choice["hash"],
                    "name": choice["label"],
                    "votes": choice["votes"],
                }
            )

        poll.choices = new_choices
        poll.save(update_fields=["choices"])


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ("misago_polls", "0002_move_data"),
    ]

    operations = [
        migrations.RunPython(
            update_polls_choices,
            migrations.RunPython.noop,
        ),
    ]
