# Generated by Django 4.2.10 on 2024-08-27 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("misago_threads", "0014_plugin_data"),
        ("misago_categories", "0013_new_behaviors"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("misago_readtracker", "0004_auto_20171015_2010"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReadCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("read_time", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="misago_categories.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReadThread",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("read_time", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="misago_categories.category",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="misago_threads.thread",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="PostRead",
        ),
        migrations.AddConstraint(
            model_name="readthread",
            constraint=models.UniqueConstraint(
                fields=("user", "thread"), name="uniq_user_thread"
            ),
        ),
        migrations.AddConstraint(
            model_name="readcategory",
            constraint=models.UniqueConstraint(
                fields=("user", "category"), name="uniq_user_category"
            ),
        ),
    ]
