# Generated by Django 4.2.10 on 2024-08-24 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("misago_readtracker", "0005_readthread_readcategory"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PostRead",
        ),
    ]
