#!/bin/bash
cd misago

echo "Extracting messages from .py and .html files..."
django-admin.py makemessages -l $1 -e html,txt,py

echo "Extracting messages from js files..."
django-admin.py makemessages -l $1 -d djangojs
