#!/bin/bash
source ~/venvs/misago06/bin/activate

PREFIX=./misago/$1/tests/
PREFIX_LEN=${#PREFIX}

TESTS=./misago/$1/tests/test_*.py
for f in $TESTS
do
  module=${f:PREFIX_LEN + 5}
  module=${module:0:${#module} - 3}
  python runtests.py misago.$1.tests.test_$module 1>/dev/null 2>/tmp/error
  errors=`tail -n1 /tmp/error`

  if [ "$2" == "md" ] ; then
    if [ "$errors" == "OK" ] ; then
      echo "    * [x] $module"
    else
      echo "    * [ ] $module: $errors"
    fi
  else
    if [ "$errors" == "OK" ] ; then
      echo "OK: $module"
    else
      echo "ER: $module"
    fi
  fi
done
