#!/bin/bash
APPS_WITH_TESTS=./misago/*/tests/__init__.py
for f in $APPS_WITH_TESTS
do
  APP=${f:9:${#f}-27}
  if [ "$1" == "md" ] ; then
    echo "* [ ] **$APP**"
    ./testapp $APP md
  else
    echo $APP
    echo "========================"
    ./testapp $APP
  fi
done
