# Generated by Django 4.2.7 on 2023-12-05 19:22

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("misago_categories", "0010_alter_rolecategoryacl_category_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="plugin_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AddIndex(
            model_name="category",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["plugin_data"], name="misago_cate_plugin__15709c_gin"
            ),
        ),
    ]
