# Generated by Django 4.2.10 on 2024-06-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("misago_categories", "0012_categories_trees_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="allow_list_access",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="category",
            name="allow_polls",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="category",
            name="limit_threads_visibility",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="category",
            name="unapproved_posts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="category",
            name="unapproved_threads",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
