# Generated by Django 4.2.10 on 2025-10-21 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("misago_categories", "0013_new_behaviors"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="last_post_on",
            new_name="last_posted_at",
        ),
    ]
