# Generated by Django 4.2.10 on 2026-03-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("misago_categories", "0014_rename_last_post_on_category_last_posted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="allow_solutions",
            field=models.BooleanField(default=False),
        ),
    ]
