# Generated by Django 4.2.10 on 2026-04-08 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("misago_categories", "0014_rename_last_post_on_category_last_posted_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="require_edits_approval",
        ),
    ]
