# Generated by Django 4.2.10 on 2026-04-24 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("misago_categories", "0015_remove_category_require_edits_approval"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="is_closed",
        ),
    ]
