# Generated by Django 4.2.10 on 2026-04-23 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("misago_categories", "0015_remove_category_require_edits_approval"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="is_closed",
            new_name="is_locked",
        ),
    ]
