# Generated by Django 4.2.10 on 2025-06-07 23:17

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("misago_categories", "0013_new_behaviors"),
        ("misago_threads", "0018_update_attachments_markup"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThreadUpdate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plugin_data", models.JSONField(default=dict)),
                ("actor_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "hidden_by_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("action", models.CharField(max_length=32)),
                (
                    "context",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "context_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("context_id", models.PositiveIntegerField(blank=True, null=True)),
                ("is_hidden", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("hidden_at", models.DateTimeField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hidden_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="misago_categories.category",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="updates",
                        to="misago_threads.thread",
                    ),
                ),
            ],
            options={
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["plugin_data"], name="misago_thre_plugin__a3a1a5_gin"
                    ),
                    models.Index(
                        fields=["thread", "created_at"],
                        name="misago_thread_update_created",
                    ),
                    models.Index(
                        condition=models.Q(("context_id__isnull", False)),
                        fields=["context_type", "context_id"],
                        name="misago_thread_update_context",
                    ),
                ],
            },
        ),
    ]
