# Generated by Django 4.2.10 on 2025-01-25 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("misago_threads", "0014_plugin_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="metadata",
            field=models.JSONField(default=dict),
        ),
    ]
