# Generated by Django 4.2.10 on 2025-02-18 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("misago_threads", "0015_post_metadata"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="mentions",
        ),
    ]
