# Generated by Django 4.2.10 on 2025-02-18 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("misago_threads", "0016_remove_post_mentions"),
        ("misago_notifications", "0002_migrate_threads_subscriptions"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Subscription",
        ),
    ]
