# Generated by Django 5.2.15 on 2026-08-09 02:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("misago_attachments", "0005_attachment_clean_names_populate_slugs"),
        ("misago_threads", "0017_delete_subscription"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="original",
            new_name="content",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="parsed",
            new_name="content_parsed",
        ),
    ]
