# Generated by Django 4.2.10 on 2025-09-02 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("misago_categories", "0013_new_behaviors"),
        ("misago_threads", "0018_remove_poll_poll_vote_related_names"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="post",
            name="misago_thre_search__b472a2_gin",
        ),
        migrations.RemoveIndex(
            model_name="post",
            name="misago_post_has_open_repo_part",
        ),
        migrations.RemoveIndex(
            model_name="post",
            name="misago_post_is_hidden_part",
        ),
        migrations.RemoveIndex(
            model_name="post",
            name="misago_thre_thread__4e5114_idx",
        ),
        migrations.RemoveIndex(
            model_name="post",
            name="misago_thre_poster__eefeb2_idx",
        ),
        migrations.RemoveField(
            model_name="thread",
            name="participants",
        ),
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="misago_categories.category",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="poster",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="thread",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="misago_threads.thread",
            ),
        ),
    ]
