# Generated by Django 4.2.10 on 2025-05-25 22:55

from django.db import migrations

from ...parser.parse import parse


def reparse_posts(apps, _):
    Post = apps.get_model("misago_threads", "Post")

    queryset = Post.objects.filter(is_event=False).order_by("-id")
    for post in queryset.iterator(chunk_size=20):
        parsing_result = parse(post.original)

        post.parsed = parsing_result.html
        post.search_document = parsing_result.text
        post.metadata = parsing_result.metadata

        post.save(update_fields=["parsed", "search_document", "metadata"])


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("misago_threads", "0018_update_attachments_markup"),
    ]

    operations = []
