# Generated by Django 4.2.10 on 2025-06-08 00:05

from django.db import migrations


def delete_events(apps, _):
    Post = apps.get_model("misago_threads", "Post")
    Post.objects.filter(is_event=True).delete()


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ("misago_threads", "0018_update_attachments_markup"),
        ("misago_threadupdates", "0002_convert_events_to_thread_updates"),
    ]

    operations = [
        migrations.RunPython(
            delete_events,
            migrations.RunPython.noop,
        ),
        migrations.RunSQL(
            """
            UPDATE misago_threads_thread as t
            SET last_post_id = (
                SELECT p.id from misago_threads_post as p
                WHERE p.thread_id = t.id
                ORDER BY p.id DESC
                LIMIT 1
            )
            """,
            migrations.RunPython.noop,
        ),
        migrations.RemoveIndex(
            model_name="post",
            name="misago_post_is_event_part",
        ),
        migrations.RemoveIndex(
            model_name="post",
            name="misago_thre_is_even_d29c90_idx",
        ),
    ]
