# Generated by Django 4.2.10 on 2025-06-19 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("misago_categories", "0013_new_behaviors"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("misago_threads", "0019_delete_events"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="misago_categories.category",
            ),
        ),
        migrations.AlterField(
            model_name="poll",
            name="poster",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="poll",
            name="thread",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="misago_threads.thread",
            ),
        ),
        migrations.AlterField(
            model_name="pollvote",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="misago_categories.category",
            ),
        ),
        migrations.AlterField(
            model_name="pollvote",
            name="poll",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="misago_threads.poll",
            ),
        ),
        migrations.AlterField(
            model_name="pollvote",
            name="thread",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="misago_threads.thread",
            ),
        ),
        migrations.AlterField(
            model_name="pollvote",
            name="voter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
