# Generated by Django 4.2.10 on 2025-09-02 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ("misago_posts", "0002_move_data"),
        ("misago_threads", "0019_remove_post_relations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thread",
            name="best_answer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="misago_posts.post",
            ),
        ),
        migrations.AlterField(
            model_name="thread",
            name="first_post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="misago_posts.post",
            ),
        ),
        migrations.AlterField(
            model_name="thread",
            name="last_post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="misago_posts.post",
            ),
        ),
    ]
