# Generated by Django 4.2.10 on 2025-10-21 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("misago_threads", "0020_remove_poll_poll_vote_related_names"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="thread",
            name="participants",
        ),
    ]
