# Generated by Django 4.2.10 on 2025-06-08 00:05

from django.db import migrations


def delete_events(apps, _):
    Post = apps.get_model("misago_threads", "Post")
    Post.objects.filter(is_event=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("misago_threads", "0020_convert_events_to_thread_updates"),
    ]

    operations = [
        migrations.RunPython(
            delete_events,
            migrations.RunPython.noop,
        ),
    ]
