# Generated by Django 4.2.10 on 2025-10-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("misago_threads", "0021_remove_thread_participants"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="post",
            name="misago_thre_poster__eefeb2_idx",
        ),
        migrations.RemoveIndex(
            model_name="thread",
            name="misago_thre_categor_7ec8b0_idx",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="posted_on",
            new_name="posted_at",
        ),
        migrations.RenameField(
            model_name="thread",
            old_name="last_post_on",
            new_name="last_posted_at",
        ),
        migrations.RenameField(
            model_name="thread",
            old_name="started_on",
            new_name="started_at",
        ),
        migrations.AddField(
            model_name="post",
            name="hidden_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["poster", "posted_at"], name="misago_thre_poster__c27497_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="thread",
            index=models.Index(
                fields=["category", "last_posted_at"],
                name="misago_thre_categor_2a84f6_idx",
            ),
        ),
    ]
