# Generated by Django 4.2.10 on 2025-10-21 20:51

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ("misago_threads", "0022_change_timestamp_suffix_to_at"),
    ]

    operations = [
        migrations.RunSQL(
            """
            UPDATE misago_threads_post
            SET updated_at = updated_on
            WHERE updated_on > posted_at
            """,
            migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            """
            UPDATE misago_threads_post
            SET hidden_at = hidden_on
            WHERE is_hidden IS TRUE
            """,
            migrations.RunSQL.noop,
        ),
    ]
