# Generated by Django 4.2.10 on 2025-10-21 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("misago_threads", "0023_populate_post_hidden_at_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="hidden_on",
        ),
        migrations.RemoveField(
            model_name="post",
            name="updated_on",
        ),
    ]
