# Generated by Django 4.2.10 on 2025-10-23 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("misago_categories", "0014_rename_last_post_on_category_last_posted_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("misago_threads", "0024_remove_post_hidden_on_updated_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postlike",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="misago_categories.category",
            ),
        ),
        migrations.AlterField(
            model_name="postlike",
            name="liker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="postlike",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="misago_threads.post",
            ),
        ),
        migrations.AlterField(
            model_name="postlike",
            name="thread",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="misago_threads.thread",
            ),
        ),
    ]
