# Generated by Django 4.2.10 on 2025-10-30 21:56

from django.conf import settings
from django.db import migrations


def populate_last_likes(apps, _):
    Post = apps.get_model("misago_threads", "Post")
    Like = apps.get_model("misago_likes", "Like")

    queryset = Post.objects.filter(id__in=Like.objects.values("post_id")).order_by(
        "-id"
    )

    for post in queryset.iterator():
        post.likes = Like.objects.filter(post=post).count()

        likes_queryset = (
            Like.objects.filter(post=post)
            .values("user_id", "user_name")
            .order_by("-id")[: settings.MISAGO_POST_LAST_LIKES_LIMIT]
        )
        post.last_likes = [
            {"id": user["user_id"], "username": user["user_name"]}
            for user in likes_queryset
        ]

        post.save(update_fields=["likes", "last_likes"])


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ("misago_threads", "0025_remove_post_like_related_names"),
        ("misago_likes", "0002_move_data"),
    ]

    operations = [
        migrations.RunSQL(
            """
            UPDATE misago_threads_post
            SET likes = 0, last_likes = NULL
            WHERE id NOT IN (
                SELECT post_id
                FROM misago_likes_like
            )
            """,
            migrations.RunSQL.noop,
        ),
        migrations.RunPython(
            populate_last_likes,
            migrations.RunPython.noop,
        ),
    ]
