# Generated by Django 4.2.10 on 2025-12-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("misago_threads", "0027_remove_post_edit_related_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="last_edit_reason",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
