# Generated by Django 4.2.10 on 2026-02-28 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ("misago_threads", "0028_post_last_edit_reason"),
    ]

    operations = [
        migrations.RenameField(
            model_name="thread",
            old_name="best_answer",
            new_name="solution",
        ),
        migrations.RenameField(
            model_name="thread",
            old_name="best_answer_marked_on",
            new_name="solution_selected_at",
        ),
        migrations.RenameField(
            model_name="thread",
            old_name="best_answer_marked_by",
            new_name="solution_selected_by",
        ),
        migrations.RenameField(
            model_name="thread",
            old_name="best_answer_marked_by_name",
            new_name="solution_selected_by_name",
        ),
        migrations.RenameField(
            model_name="thread",
            old_name="best_answer_marked_by_slug",
            new_name="solution_selected_by_slug",
        ),
        migrations.RemoveField(
            model_name="thread",
            name="best_answer_is_protected",
        ),
        migrations.AddField(
            model_name="thread",
            name="solution_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="thread",
            name="solution_by_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="thread",
            name="solution_by_slug",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="thread",
            name="solution_selected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
