# Generated by Django 4.2.10 on 2026-03-30 18:59

from django.db import migrations


def populate_thread_solution_by(apps, _):
    Thread = apps.get_model("misago_threads", "Thread")

    queryset = (
        Thread.objects.filter(solution_by__isnull=False)
        .select_related("solution_by")
        .order_by("-id")
    )

    for thread in queryset.iterator():
        thread.solution_by_name = thread.solution_by.username
        thread.solution_by_slug = thread.solution_by.slug
        thread.save(update_fields=["solution_by_name", "solution_by_slug"])


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ("misago_threads", "0029_solutions"),
    ]

    operations = [
        migrations.RunSQL(
            """
            UPDATE misago_threads_thread t
            SET
                solution_posted_at=p.posted_at,
                solution_by_id=p.poster_id,
                solution_by_name=p.poster_name
            FROM misago_threads_post p
            WHERE t.solution_id IS NOT NULL AND t.solution_id = p.id;
            """,
            migrations.RunSQL.noop,
        ),
        migrations.RunPython(
            populate_thread_solution_by,
            migrations.RunPython.noop,
        ),
    ]
