# Generated by Django 4.2.10 on 2026-04-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("misago_threads", "0030_populate_thread_solutions"),
    ]

    operations = [
        migrations.AddField(
            model_name="thread",
            name="require_replies_approval",
            field=models.BooleanField(default=False),
        ),
    ]
