# Generated by Django 4.2.10 on 2026-04-13 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("misago_threads", "0031_thread_require_replies_approval"),
    ]

    operations = [
        migrations.RunSQL(
            """
            UPDATE misago_threads_post SET is_unapproved = False
            WHERE id IN (
                SELECT first_post_id
                FROM misago_threads_thread
                WHERE is_unapproved = True
            )
            """,
            migrations.RunSQL.noop,
        )
    ]
