# Generated by Django 4.2.10 on 2026-04-21 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("misago_threads", "0032_thread_approve_first_post"),
    ]

    operations = [
        migrations.RenameField(
            model_name="thread",
            old_name="has_events",
            new_name="has_updates",
        ),
    ]
