# Generated by Django 4.2.10 on 2026-04-23 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("misago_threads", "0033_rename_has_events_thread_has_updates"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="is_protected",
            new_name="is_locked",
        ),
        migrations.RenameField(
            model_name="thread",
            old_name="is_closed",
            new_name="is_locked",
        ),
    ]
