# Generated by Django 4.2.10 on 2026-06-01 23:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("misago_threads", "0034_delete_moved_models"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="event_context",
        ),
        migrations.RemoveField(
            model_name="post",
            name="event_type",
        ),
        migrations.RemoveField(
            model_name="post",
            name="is_event",
        ),
        migrations.RemoveField(
            model_name="thread",
            name="last_post_is_event",
        ),
    ]
