# Generated by Django 4.2.10 on 2026-06-01 22:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("misago_attachments", "0002_move_data"),
        ("misago_likes", "0002_move_data"),
        ("misago_polls", "0002_move_data"),
        ("misago_postedits", "0002_move_data"),
        ("misago_privatethreads", "0002_move_data"),
        ("misago_threads", "0034_rename_is_protected_is_closed_to_is_locked"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attachmenttype",
            name="limit_downloads_to",
        ),
        migrations.RemoveField(
            model_name="attachmenttype",
            name="limit_uploads_to",
        ),
        migrations.RemoveField(
            model_name="poll",
            name="category",
        ),
        migrations.RemoveField(
            model_name="poll",
            name="poster",
        ),
        migrations.RemoveField(
            model_name="poll",
            name="thread",
        ),
        migrations.RemoveField(
            model_name="pollvote",
            name="category",
        ),
        migrations.RemoveField(
            model_name="pollvote",
            name="poll",
        ),
        migrations.RemoveField(
            model_name="pollvote",
            name="thread",
        ),
        migrations.RemoveField(
            model_name="pollvote",
            name="voter",
        ),
        migrations.RemoveField(
            model_name="postedit",
            name="category",
        ),
        migrations.RemoveField(
            model_name="postedit",
            name="editor",
        ),
        migrations.RemoveField(
            model_name="postedit",
            name="post",
        ),
        migrations.RemoveField(
            model_name="postedit",
            name="thread",
        ),
        migrations.RemoveField(
            model_name="postlike",
            name="category",
        ),
        migrations.RemoveField(
            model_name="postlike",
            name="liker",
        ),
        migrations.RemoveField(
            model_name="postlike",
            name="post",
        ),
        migrations.RemoveField(
            model_name="postlike",
            name="thread",
        ),
        migrations.RemoveField(
            model_name="threadparticipant",
            name="thread",
        ),
        migrations.RemoveField(
            model_name="threadparticipant",
            name="user",
        ),
        migrations.RemoveField(
            model_name="post",
            name="liked_by",
        ),
        migrations.DeleteModel(
            name="Attachment",
        ),
        migrations.DeleteModel(
            name="AttachmentType",
        ),
        migrations.DeleteModel(
            name="Poll",
        ),
        migrations.DeleteModel(
            name="PollVote",
        ),
        migrations.DeleteModel(
            name="PostEdit",
        ),
        migrations.DeleteModel(
            name="PostLike",
        ),
        migrations.DeleteModel(
            name="ThreadParticipant",
        ),
    ]
