# Generated by Django 4.2.10 on 2026-06-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("misago_threads", "0035_remove_post_events_fields"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="thread",
            name="misago_thread_pinned_glob_part",
        ),
        migrations.RemoveIndex(
            model_name="thread",
            name="misago_thread_pinned_loca_part",
        ),
        migrations.RemoveIndex(
            model_name="thread",
            name="misago_thread_not_pinned_part",
        ),
        migrations.RemoveIndex(
            model_name="thread",
            name="misago_thread_not_global_part",
        ),
        migrations.RenameField(
            model_name="thread",
            old_name="weight",
            new_name="pinned",
        ),
        migrations.AddIndex(
            model_name="thread",
            index=models.Index(
                condition=models.Q(("pinned", 2)),
                fields=["pinned"],
                name="misago_thread_pin_everywh_part",
            ),
        ),
        migrations.AddIndex(
            model_name="thread",
            index=models.Index(
                condition=models.Q(("pinned", 1)),
                fields=["pinned"],
                name="misago_thread_pin_categor_part",
            ),
        ),
        migrations.AddIndex(
            model_name="thread",
            index=models.Index(
                condition=models.Q(("pinned", 0)),
                fields=["pinned"],
                name="misago_thread_not_pinned_part",
            ),
        ),
        migrations.AddIndex(
            model_name="thread",
            index=models.Index(
                condition=models.Q(("pinned__lt", 2)),
                fields=["pinned"],
                name="misago_thread_not_everywh_part",
            ),
        ),
    ]
