# Generated by Django 4.2.10 on 2026-06-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("misago_threads", "0038_thread_hidden"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="hidden_reason",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
