# Generated by Django 5.2.15 on 2026-08-12 22:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("misago_threads", "0039_thread_post_locked"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="post",
            name="misago_thre_search__b472a2_gin",
        ),
        migrations.RemoveField(
            model_name="post",
            name="search_document",
        ),
        migrations.RemoveField(
            model_name="post",
            name="search_vector",
        ),
    ]
