# Generated by Django 4.2.10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("misago_threads", "0039_post_hidden_reason"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="thread",
            name="has_open_reports",
        ),
        migrations.RemoveField(
            model_name="thread",
            name="has_reported_posts",
        ),
        migrations.RemoveIndex(
            model_name="thread",
            name="misago_thread_has_reporte_part",
        ),
    ]
