# Generated by Django 4.2.10 on 2025-05-24 23:25

import django.contrib.postgres.search
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PostSnapshot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_id", models.PositiveIntegerField(db_index=True)),
                ("original", models.TextField()),
                ("parsed", models.TextField()),
                ("checksum", models.CharField(max_length=64)),
                ("search_document", models.TextField(blank=True, null=True)),
                ("search_vector", django.contrib.postgres.search.SearchVectorField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
