# Generated by Django 4.2.10 on 2025-10-23 19:04

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ("misago_likes", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            """
            INSERT INTO misago_likes_like (
                id,
                category_id,
                thread_id,
                user_id,
                user_name,
                user_slug,
                liked_at
            )
            SELECT
                id,
                category_id,
                thread_id,
                liker_id,
                liker_name,
                liker_slug,
                liked_on
            FROM misago_threads_postlike;
            """,
            migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            """
            SELECT SETVAL(
                'misago_likes_like_id_seq',
                (SELECT last_value FROM misago_threads_postlike_id_seq)
            );
            """,
            migrations.RunSQL.noop,
        ),
    ]
