# Generated by Django 4.2.10 on 2025-06-07 23:17

from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.models import ContentType
from django.db import migrations

from ...categories.models import Category
from ...core.utils import slugify

EVENT_TYPES = {
    "pinned_globally": "pinned_everywhere",
    "pinned_locally": "pinned_category",
    "closed": "locked",
    "opened": "unlocked",
    "hid": "hidden",
    "unhid": "unhidden",
    "split": "split_posts_from",
    "entered_thread": "member_joined",
    "tookover": "took_ownership",
    "removed_owner": "removed_member",
    "added_participant": "added_member",
    "owner_left": "member_left",
    "participant_left": "member_left",
}


def convert_events_to_thread_events(apps, _):
    Post = apps.get_model("misago_threads", "Post")
    ThreadEvent = apps.get_model("misago_threadevents", "ThreadEvent")

    for post in Post.objects.filter(is_event=True).order_by("id"):
        detail = None
        content_type = None
        object_id = None

        if parsed_context := get_event_content_data(apps, post.event_context):
            detail, content_type, object_id = parsed_context

        thread_event = ThreadEvent.objects.create(
            category_id=post.category_id,
            thread_id=post.thread_id,
            actor_id=post.poster_id,
            actor_name=post.poster_name,
            actor_slug=slugify(post.poster_name),
            hidden_by_id=post.hidden_by_id,
            hidden_by_name=post.hidden_by_name,
            hidden_by_slug=slugify(post.hidden_by_name),
            event_type=EVENT_TYPES.get(post.event_type, post.event_type),
            detail=detail,
            content_type=content_type,
            object_id=object_id,
            is_hidden=post.is_hidden,
            hidden_at=post.hidden_on,
        )

        ThreadEvent.objects.filter(id=thread_event.id).update(created_at=post.posted_on)


def get_event_content_data(
    apps, event_context: dict | None
) -> tuple[str, int, str] | None:
    if not event_context:
        return None

    if from_category := event_context.get("from_category"):
        detail = from_category["name"]
        content_type = ContentType.objects.get_for_model(Category)
        object_id = get_object_id_from_url(from_category["url"])
        return detail, content_type, object_id

    if user := event_context.get("user"):
        detail = user["username"]
        content_type = ContentType.objects.get_for_model(get_user_model())
        object_id = user.get("id") or get_object_id_from_url(user["url"])
        return detail, content_type, object_id

    if old_title := event_context.get("old_title"):
        detail = old_title
        return detail, None, None

    if merged_thread := event_context.get("merged_thread"):
        detail = merged_thread
        return detail, None, None

    return None


def get_object_id_from_url(url: str) -> int:
    return int(url[:-1].split("/")[-1])


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("misago_threadevents", "0001_threadevent"),
    ]

    operations = [
        migrations.RunPython(
            convert_events_to_thread_events,
            migrations.RunPython.noop,
        ),
    ]
