"""
Python Social Auth doesn't provide information about proper names for OAuth sites,
so we are using this file for overrides whenever name is different than `provider.name.title`
"""

BACKENDS_NAMES = {
    'angel': "AngelList",
    'aol': "AOL",
    'arcgis': "ArcGIS",
    'azuread-oauth2': "Azure Active Directory",
    'azuread-b2c-oauth2': "Azure Active Directory B2C",
    'azuread-tenant-oauth2': "Azure Active Directory tenant",
    'battlenet-oauth2': "Blizzard Battle.net",
    'belgiumeid': "Belgium EID",
    'bitbucket-oauth2': "Bitbucket",
    'bungie': "Bungie.net",
    'chatwork': "ChatWork",
    'classlink': "ClassLink",
    'digitalocean': "DigitalOcean",
    'douban-oauth2': "Douban",
    'dropbox-oauth2': "Dropbox",
    'echosign': "Adobe Sign",
    'eveonline': "EVE Online",
    'evernote-sandbox': "Evernote (sandbox)",
    'facebook-app': "Facebook",
    'google-appengine': "Google App Engine",
    'github': "GitHub",
    'github-org': "GitHub Organization",
    'github-team': "GitHub Team",
    'github-enterprise': "GitHub Enterprise",
    'github-enterprise-org': "GitHub Enterprise Organization",
    'github-enterprise-team': "GitHub Enterprise Team",
    'gitlab': "GitLab",
    'goclio': "Clio.com",
    'goclioeu': "Clio.eu",
    'google': "Google",
    'google-oauth': "Google",
    'google-oauth2': "Google",
    'google-plus': "Google Plus",
    'google-openidconnect': "Google",
    'itembase-sandbox': "Itembase (sandbox)",
    'justgiving': "JustGiving",
    'khanacademy-oauth1': "Khan Academy",
    'lastfm': "Last.fm",
    'line': "LINE",
    'linkedin': "LinkedIn",
    'live': "Live Connect",
    'livejournal': "LiveJournal",
    'loginradius': "LoginRadius",
    'mailchimp': "MailChimp",
    'mailru-oauth2': "Mail.ru",
    'mapmyfitness': "MapMyFitness",
    'mediawiki': "MediaWiki",
    'mendeley-oauth2': "Mendeley",
    'microsoft-graph': "Microsoft",
    'mineid': "MineID",
    'nationbuilder': "NationBuilder",
    'naver': "NAVER",
    'actionid-openid': "NGP VAN ActionID",
    'nk': "nk.pl",
    'odnoklassniki-oauth2': "OK.RU",
    'odnoklassniki-app': "OK.RU",
    'openshift': "OpenShift",
    'openstreetmap': "PpenStreetMap",
    'orcid': "ORCID",
    'professionali': "Professionali.ru",
    'qq': "QQ",
    'rdio-oauth1': "Pandora",
    'rdio-oauth2': "Pandora",
    'salesforce-oauth2': "Salesforce",
    'salesforce-oauth2-sandbox': "Salesforce (sandbox)",
    'saml': "SAML",
    'shimmering': "Shimmering Verify",
    'stackoverflow': "StackExchange",
    'stocktwits': "StockTwits",
    'opensuse': "Open SUSE OpenId",
    'datagouv': "uData",
    'vimeo-oauth2': "Vimeo",
    'vk': "VK",
    'weixinapp': "Weixin",
    'yahoo-oauth': "Yahoo",
    'yahoo-oauth2': "Yahoo",
    'yammer-staging': "Yammer (staging)",
    'yandex-openid': "Yandex",
    'yandex-oauth2': "Yandex",
    'yaru': "Yandex",
}
