# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 21:56
from __future__ import unicode_literals

from django.db import migrations
import misago.core.pgutils


class Migration(migrations.Migration):

    dependencies = [
        ('misago_users', '0008_ban_registration_only'),
    ]

    operations = [
        migrations.RunSQL(
            "DROP INDEX misago_users_user_is_staff_partial",
            """
                CREATE INDEX misago_users_user_is_staff_partial
                ON misago_users_user(is_staff)
                WHERE is_staff = TRUE
            """,
        ),
        migrations.RunSQL(
            "DROP INDEX misago_users_user_requires_activation_partial",
            """
                CREATE INDEX misago_users_user_requires_activation_partial
                ON misago_users_user(requires_activation)
                WHERE requires_activation > 0
            """,
        ),

        migrations.AddIndex(
            model_name='user',
            index=misago.core.pgutils.PgPartialIndex(fields=[b'is_staff'], name='misago_user_is_staf_f5a0fa_part', where={b'is_staff': True}),
        ),
        migrations.AddIndex(
            model_name='user',
            index=misago.core.pgutils.PgPartialIndex(fields=[b'requires_activation'], name='misago_user_require_50b161_part', where={b'requires_activation__gt': 0}),
        ),
    ]
