# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 22:15
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misago_users', '0009_redo_partial_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
