# Generated by Django 1.11.15 on 2018-11-13 17:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('misago_users', '0015_user_agreements'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_by', models.PositiveIntegerField(choices=[(1, 'By User'), (2, 'By Staff'), (3, 'By System')], default=1)),
            ],
            options={
                'get_latest_by': 'deleted_on',
            },
        ),
    ]
