# Generated by Django 2.2.3 on 2019-08-26 01:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('misago_users', '0020_set_dj_partial_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_by', models.PositiveIntegerField(choices=[(1, 'By User'), (2, 'By Staff'), (3, 'By System')], db_index=True, default=1)),
            ],
            options={
                'ordering': ['deleted_on'],
            },
        ),
    ]
