# Generated by Django 3.2.15 on 2022-09-27 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misago_users', '0022_deleteduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sso_id',
        ),
    ]
