# Generated by Django 3.2.15 on 2023-04-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("misago_users", "0023_remove_user_sso_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notify_new_private_threads_by_followed",
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name="user",
            name="notify_new_private_threads_by_other_users",
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name="user",
            name="unread_notifications",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="watch_new_private_threads_by_followed",
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name="user",
            name="watch_new_private_threads_by_other_users",
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name="user",
            name="watch_replied_threads",
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name="user",
            name="watch_started_threads",
            field=models.PositiveIntegerField(default=2),
        ),
    ]
