# Generated by Django 4.2.10 on 2025-02-18 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("misago_users", "0029_users_permissions_nonnull"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="subscribe_to_replied_threads",
        ),
        migrations.RemoveField(
            model_name="user",
            name="subscribe_to_started_threads",
        ),
    ]
