# Generated by Django 4.2.10 on 2025-04-17 15:57

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import BtreeGistExtension, TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("misago_users", "0030_remove_user_subscribe_to_replied_threads_and_more"),
    ]

    operations = [
        BtreeGistExtension(),
        TrigramExtension(),
        migrations.AddIndex(
            model_name="user",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["username"], name="misago_user_username_trgrm"
            ),
        ),
    ]
