# Generated by Django 4.2.10 on 2025-08-10 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("misago_users", "0031_add_user_username_trigram_index"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="limits_private_thread_invites_to",
            new_name="allow_new_private_threads_by",
        ),
    ]
