# Generated by Django 4.2.10 on 2025-10-21 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("misago_users", "0032_rename_private_threads_preference"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="last_posted_on",
            new_name="last_posted_at",
        ),
    ]
