# Generated by Django 4.2.10 on 2026-04-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("misago_users", "0033_rename_last_posted_on_user_last_posted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="require_content_approval",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                condition=models.Q(("require_content_approval", True)),
                fields=["require_content_approval"],
                name="misago_user_req_content_approv",
            ),
        ),
    ]
