# Generated by Django 5.2.15 on 2026-09-09 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misago_users', '0034_user_require_content_approval_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ban',
            old_name='staff_message',
            new_name='team_reason',
        ),
        migrations.RenameField(
            model_name='bancache',
            old_name='staff_message',
            new_name='team_reason',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='avatar_lock_staff_message',
            new_name='avatar_lock_team_reason',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_active_staff_message',
            new_name='deactivated_reason',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='signature_lock_staff_message',
            new_name='signature_lock_team_reason',
        ),
    ]
