# Generated by Django 5.2.15 on 2026-09-07 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misago_users', '0035_rename_staff_message_ban_team_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ban',
            old_name='team_message',
            new_name='team_reason',
        ),
        migrations.RenameField(
            model_name='bancache',
            old_name='team_message',
            new_name='team_reason',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='avatar_lock_team_message',
            new_name='avatar_lock_team_reason',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_active_team_message',
            new_name='is_active_team_reason',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='signature_lock_team_message',
            new_name='signature_lock_team_reason',
        ),
    ]
