# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovedId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('old_id', models.CharField(max_length=255)),
                ('new_id', models.CharField(max_length=255)),
            ],
        ),
    ]
