# Generated by Django 2.2.1 on 2019-05-19 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("misago_conf", "0002_cache_version")]

    operations = [
        migrations.RemoveField(model_name="setting", name="description"),
        migrations.RemoveField(model_name="setting", name="field_extra"),
        migrations.RemoveField(model_name="setting", name="form_field"),
        migrations.RemoveField(model_name="setting", name="group"),
        migrations.RemoveField(model_name="setting", name="legend"),
        migrations.RemoveField(model_name="setting", name="name"),
        migrations.RemoveField(model_name="setting", name="order"),
        migrations.DeleteModel(name="SettingsGroup"),
    ]
