# Generated by Django 2.2.1 on 2019-05-19 00:16

from django.db import migrations


def create_settings(apps, _):
    # This migration builds list of existing settings, and then
    # creates settings not already in database
    Setting = apps.get_model("misago_conf", "Setting")
    existing_settings = Setting.objects.values_list("setting", flat=True)
    raise Exception(existing_settings)


class Migration(migrations.Migration):

    dependencies = [
        ("misago_conf", "0003_simplify_models"),
        ("misago_core", "0003_delete_cacheversion"),
        ("misago_threads", "0012_set_dj_partial_indexes"),
        ("misago_users", "0020_set_dj_partial_indexes"),
    ]

    operations = [migrations.RunPython(create_settings)]
