# Generated by Django 3.2.15 on 2022-09-27 18:45

from django.db import migrations

settings = (
    "enable_sso",
    "sso_public_key",
    "sso_private_key",
    "sso_url",
)


def delete_settings(apps, _):
    Setting = apps.get_model("misago_conf", "Setting")
    Setting.objects.filter(setting__in=settings).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("misago_conf", "0005_add_sso_settings"),
    ]

    operations = [migrations.RunPython(delete_settings)]
