# Generated by Django 4.2.10 on 2024-06-20 21:30

from django.conf import settings
from django.db import migrations

THREADS_ON_INDEX = getattr(settings, "MISAGO_THREADS_ON_INDEX", True)


def create_setting(apps, _):
    Setting = apps.get_model("misago_conf", "Setting")
    Setting.objects.create(
        setting="index_view",
        dry_value="threads" if THREADS_ON_INDEX else "categories",
        is_public=True,
    )


def remove_setting(apps, _):
    Setting = apps.get_model("misago_conf", "Setting")
    Setting.objects.filter(setting="index_view").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("misago_conf", "0012_add_oauth2_pkce_settings"),
    ]

    operations = [migrations.RunPython(create_setting, remove_setting)]
