# Generated by Django 4.2.10 on 2024-07-03 17:12

from django.db import migrations
from ...threads.enums import ThreadsListsPolling

settings = {
    "threads_list_item_categories_component": {
        "dry_value": "breadcrumbs",
    },
    "threads_list_categories_component": {
        "dry_value": "dropdown",
    },
    "threads_lists_polling": {
        "python_type": "int",
        "dry_value": ThreadsListsPolling.ENABLED.value,
    },
}


def create_setting(apps, _):
    Setting = apps.get_model("misago_conf", "Setting")

    for setting, data in settings.items():
        Setting.objects.create(setting=setting, **data)


def remove_setting(apps, _):
    Setting = apps.get_model("misago_conf", "Setting")
    Setting.objects.filter(setting__in=settings).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("misago_conf", "0013_add_index_view_setting"),
    ]

    operations = [migrations.RunPython(create_setting, remove_setting)]
