# Generated by Django 4.2.10 on 2024-07-03 17:12

from django.db import migrations


def create_setting(apps, _):
    Setting = apps.get_model("misago_conf", "Setting")
    Setting.objects.create(
        setting="threads_list_item_categories_component",
        dry_value="breadcrumbs",
    )
    Setting.objects.create(
        setting="threads_list_categories_component",
        dry_value="dropdown",
    )


def remove_setting(apps, _):
    Setting = apps.get_model("misago_conf", "Setting")
    Setting.objects.filter(
        setting__in=(
            "threads_list_item_categories_component",
            "threads_list_categories_component",
        ),
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("misago_conf", "0013_add_index_view_setting"),
    ]

    operations = [migrations.RunPython(create_setting, remove_setting)]
