# Generated by Django 4.2.10 on 2024-12-15 12:07

from django.db import migrations

from ..hydrators import dehydrate_value

setting = {
    "setting": "merge_repeated_postings",
    "python_type": "int",
    "dry_value": 20 * 60,
    "is_public": False,
}


def create_setting(apps, _):
    Setting = apps.get_model("misago_conf", "Setting")

    Setting.objects.create(
        setting=setting["setting"],
        python_type=setting["python_type"],
        dry_value=setting["dry_value"],
        is_public=setting["is_public"],
    )


def remove_setting(apps, _):
    Setting = apps.get_model("misago_conf", "Setting")
    Setting.objects.filter(setting=setting["setting"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("misago_conf", "0014_add_threads_lists_settings"),
    ]

    operations = [migrations.RunPython(create_setting, remove_setting)]
