# Generated by Django 4.2.10 on 2024-12-15 12:07

from django.db import migrations

from ..operations import CreateSetting


class Migration(migrations.Migration):

    dependencies = [
        ("misago_conf", "0014_add_threads_lists_settings"),
    ]

    operations = [
        CreateSetting(
            setting="merge_concurrent_posts",
            python_type="int",
            dry_value=20,
        ),
    ]
