# Generated by Django 4.2.10 on 2024-12-15 12:07

from django.db import migrations

from ..operations import CreateSetting


class Migration(migrations.Migration):

    dependencies = [
        ("misago_conf", "0015_add_merge_concurrent_posts_setting"),
    ]

    operations = [
        CreateSetting(
            setting="flood_control",
            python_type="int",
            dry_value=20,
        ),
    ]
