# Generated by Django 4.2.10 on 2025-02-18 22:36

from django.db import migrations

from ..operations import DeleteSetting


class Migration(migrations.Migration):

    dependencies = [
        ("misago_conf", "0017_add_new_attachments_settings"),
    ]

    operations = [
        DeleteSetting(setting="subscribe_start"),
        DeleteSetting(setting="subscribe_reply"),
    ]
