# Generated by Django 4.2.10 on 2025-06-09 20:32

from django.db import migrations
from ..operations import CreateSetting


class Migration(migrations.Migration):

    dependencies = [
        ("misago_conf", "0018_delete_subscriptions"),
    ]

    operations = [
        CreateSetting(
            setting="thread_updates_per_page",
            python_type="int",
            dry_value=30,
        ),
    ]
