# Generated by Django 4.2.10 on 2025-06-09 22:11

from django.db import migrations

from ..operations import DeleteSetting


class Migration(migrations.Migration):

    dependencies = [
        ("misago_conf", "0019_add_thread_updates_settings"),
    ]

    operations = [
        DeleteSetting(setting="events_per_page"),
    ]
