# Generated by Django 4.2.10 on 2025-06-20 22:57

from django.db import migrations

from ...polls.enums import AllowedPublicPolls
from ..operations import CreateSetting


class Migration(migrations.Migration):

    dependencies = [
        ("misago_conf", "0020_delete_events"),
    ]

    operations = [
        CreateSetting(
            setting="allow_public_polls",
            dry_value=AllowedPublicPolls.ALLOWED.value,
        ),
    ]
