# Generated by Django 4.2.10 on 2025-06-20 22:57

from django.db import migrations

from ...polls.enums import PublicPollsAvailability
from ..operations import CreateSetting


class Migration(migrations.Migration):

    dependencies = [
        ("misago_conf", "0020_delete_events"),
    ]

    operations = [
        CreateSetting(
            setting="poll_question_min_length",
            python_type="int",
            dry_value=8,
        ),
        CreateSetting(
            setting="poll_question_max_length",
            python_type="int",
            dry_value=150,
        ),
        CreateSetting(
            setting="poll_max_choices",
            python_type="int",
            dry_value=10,
        ),
        CreateSetting(
            setting="poll_choice_min_length",
            python_type="int",
            dry_value=3,
        ),
        CreateSetting(
            setting="poll_choice_max_length",
            python_type="int",
            dry_value=80,
        ),
        CreateSetting(
            setting="enable_public_polls",
            dry_value=PublicPollsAvailability.ENABLED.value,
        ),
    ]
