# Generated by Django 5.2.15 on 2026-09-27 00:33

from django.db import migrations

from ..operations import CreateSetting


class Migration(migrations.Migration):
    dependencies = [
        ("misago_conf", "0021_add_new_polls_settings"),
    ]

    operations = [
        CreateSetting(
            setting="max_search_query_length",
            python_type="int",
            dry_value=150,
        ),
        CreateSetting(
            setting="min_search_term_length",
            python_type="int",
            dry_value=4,
        ),
        CreateSetting(
            setting="user_min_search_interval",
            python_type="int",
            dry_value=5,
        ),
        CreateSetting(
            setting="guest_min_search_interval",
            python_type="int",
            dry_value=12,
        ),
        CreateSetting(
            setting="search_log_retention",
            python_type="int",
            dry_value=45,
        ),
    ]
