# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-25 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import misago.cache.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CacheVersion',
            fields=[
                ('cache', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('version', models.CharField(default=misago.cache.utils.generate_version_string, max_length=8)),
            ],
        ),
    ]
