# Generated by Django 4.2.8 on 2023-12-28 14:45

from django.db import migrations

from ..enums import CacheName
from ..operations import StartCacheVersioning


class Migration(migrations.Migration):
    dependencies = [
        ("misago_cache", "0001_initial"),
    ]

    operations = [
        StartCacheVersioning(CacheName.GROUPS),
        StartCacheVersioning(CacheName.MODERATORS),
        StartCacheVersioning(CacheName.PERMISSIONS),
    ]
