# Generated by Django 4.2.10 on 2024-06-17 17:06

from django.db import migrations

from ..enums import CacheName
from ..operations import StartCacheVersioning


class Migration(migrations.Migration):
    dependencies = [
        ("misago_cache", "0002_new_permissions"),
    ]

    operations = [
        StartCacheVersioning(CacheName.CATEGORIES),
    ]
