# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.6.8
      - image: circleci/postgres:9.6.5-alpine-ram

    environment:
      LOCAL_BIN: /home/circleci/.local/bin
      stage: circleci
      project_config_dir: webapp/src/community_app/settings/
      AWS_ACCESS_KEY_ID: ~
      AWS_SECRET_ACCESS_KEY: ~
      AWS_DEFAULT_REGION: us-east-1
      POSTGRES_HOST: localhost # Does not set configuration on DB, intended only for reference below
      POSTGRES_USER: root
      POSTGRES_DB: circle_test
      POSTGRES_PORT: 5432

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "webapp/requirements.txt" }}-{{ checksum "webapp/requirements-test.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Upgrade pip and install dependencies
          command: |
            pip install --user -U pip==20.2.2
            pip freeze
            pip install --user -r webapp/requirements-test.txt

      - run:
          name: Install dependencies
          command: |
            wget https://github.com/jwilder/dockerize/releases/download/v0.3.0/dockerize-linux-amd64-v0.3.0.tar.gz
            tar -C $LOCAL_BIN -xzvf dockerize-linux-amd64-v0.3.0.tar.gz
            rm dockerize-linux-amd64-v0.3.0.tar.gz

      - run:
          name: Set python path
          command: |
            echo 'export PYTHONPATH=$PYTHONPATH:webapp/src/' >> $BASH_ENV

      - run:
          name: Waiting for Postgres to be ready
          command: $LOCAL_BIN/dockerize -wait tcp://$POSTGRES_HOST:$POSTGRES_PORT -timeout 1m

      - run:
          name: run test
          command: |
            $LOCAL_BIN/pytest -rf --cov

      - run:
          name: generate coverage reports
          command: |
            $LOCAL_BIN/coverage html -d artifacts
            $LOCAL_BIN/coverage-badge -o artifacts/coverage.svg

      - store_artifacts:
          path: artifacts

      - save_cache:
          paths:
            - "/root/.local"
          key: v1-dependencies-{{ checksum "webapp/requirements.txt" }}-{{ checksum "webapp/requirements-test.txt" }}

  build:
    docker:
      - image: circleci/node:12.18

    steps:
      - checkout

      - run:
          name: try building frontend
          command: |
            cd frontend
            npm install
            npm install gulp
            npx gulp build

workflows:
  version: 2
  build_and_test:
    jobs:
      - test:
          context: Github Repo Access
      - build:
          context: Github Repo Access
