# Generated by Django 4.2.10 on 2025-12-17 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("misago_threads", "0027_remove_post_edit_related_names"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("misago_categories", "0014_rename_last_post_on_category_last_posted_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostEdit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="misago_categories.category",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="misago_threads.post",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="misago_threads.thread",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("user_name", models.CharField(max_length=255)),
                ("user_slug", models.CharField(max_length=255)),
                (
                    "edit_reason",
                    models.CharField(max_length=255, null=True, blank=True),
                ),
                ("original_old", models.TextField()),
                ("original_new", models.TextField()),
                ("original_added", models.PositiveIntegerField(default=0)),
                ("original_removed", models.PositiveIntegerField(default=0)),
                ("attachments", models.JSONField(default=list)),
                ("attachments_added", models.PositiveIntegerField(default=0)),
                ("attachments_removed", models.PositiveIntegerField(default=0)),
                ("edited_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("plugin_data", models.JSONField(default=dict)),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
