# Generated by Django 4.2.10 on 2025-12-17 17:16

from django.db import migrations

from ..diff import diff_text


def migrate_edits_data_from_threads(apps, schema_editor):
    LegacyPostEdit = apps.get_model("misago_threads", "PostEdit")
    PostEdit = apps.get_model("misago_postedits", "PostEdit")

    queryset = LegacyPostEdit.objects.order_by("id")
    for legacy_edit in queryset.iterator(chunk_size=100):
        diff = diff_text(legacy_edit.edited_from, legacy_edit.edited_to)
        PostEdit.objects.create(
            category_id=legacy_edit.category_id,
            thread_id=legacy_edit.thread_id,
            post_id=legacy_edit.post_id,
            user_id=legacy_edit.editor_id,
            user_name=legacy_edit.editor_name,
            user_slug=legacy_edit.editor_slug,
            original_before=legacy_edit.edited_from,
            original_after=legacy_edit.edited_to,
            original_added=diff.added,
            original_removed=diff.removed,
            edited_at=legacy_edit.edited_on,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("misago_postedits", "0001_initial"),
    ]

    atomic = False

    operations = [
        migrations.RunPython(
            migrate_edits_data_from_threads, migrations.RunPython.noop
        ),
    ]
