# Generated by Django 4.2.10 on 2026-05-06 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("misago_postedits", "0002_move_data"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="postedit",
            new_name="misago_post_plugin__59ca89_gin",
            old_name="misago_edit_plugin__7827ec_gin",
        ),
    ]
