#!/bin/bash
echo 'Building production assets...'
ember build --environment=production

echo 'Deleting old assets...'
rm -rf ../static/misago/css
rm -rf ../static/misago/fonts
rm -rf ../static/misago/img
rm -rf ../static/misago/js

echo 'Copying assets to misago/static...'
mkdir -p ../static/misago/css/

cp ./dist/misago/css/misago.css ../static/misago/css/misago.css
cp -r ./dist/misago/fonts/ ../static/misago/fonts/
cp -r ./dist/misago/img/ ../static/misago/img/
cp -r ./dist/misago/js/ ../static/misago/js/
echo 'Done!'
