"""users

Revision ID: cf6bc6c927e6
Revises: 59c5ea8d68aa
Create Date: 2022-07-10 21:32:44.013001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cf6bc6c927e6"
down_revision = "59c5ea8d68aa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "misago_users",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("slug", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("email_hash", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=150), nullable=True),
        sa.Column("password", sa.String(length=255), nullable=True),
        sa.Column("group_id", sa.BigInteger(), nullable=False),
        sa.Column("groups_ids", sa.JSON(), nullable=False),
        sa.Column("perms_id", sa.String(length=255), nullable=False),
        sa.Column(
            "avatar_type",
            sa.Enum("GRAVATAR", "UPLOAD", name="avatartype"),
            nullable=False,
        ),
        sa.Column("avatars", sa.JSON(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_moderator", sa.Boolean(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("extra", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"], ["misago_user_groups.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("email_hash"),
        sa.UniqueConstraint("slug"),
    )
    op.create_index(
        "misago_users_admins",
        "misago_users",
        ["is_admin"],
        unique=False,
        postgresql_where=sa.text("is_admin = true"),
    )
    op.create_index(
        "misago_users_full_names_search",
        "misago_users",
        ["full_name"],
        unique=False,
        postgresql_ops={"full_name": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.create_index(
        "misago_users_inactive",
        "misago_users",
        ["is_active"],
        unique=False,
        postgresql_where=sa.text("is_active = false"),
    )
    op.create_index(
        "misago_users_moderators",
        "misago_users",
        ["is_moderator"],
        unique=False,
        postgresql_where=sa.text("is_moderator = true"),
    )
    op.create_index(
        "misago_users_slugs_search",
        "misago_users",
        ["slug"],
        unique=False,
        postgresql_ops={"slug": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.create_index(
        "misago_users_without_full_names",
        "misago_users",
        ["full_name"],
        unique=False,
        postgresql_where=sa.text("full_name IS NULL"),
    )
    op.create_table(
        "misago_user_group_memberships",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("group_id", sa.BigInteger(), nullable=False),
        sa.Column("is_main", sa.Boolean(), nullable=False, index=True),
        sa.ForeignKeyConstraint(
            ["group_id"], ["misago_user_groups.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["misago_users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("misago_user_group_memberships")
    op.drop_index(
        "misago_users_without_full_names",
        table_name="misago_users",
        postgresql_where=sa.text("full_name IS NULL"),
    )
    op.drop_index(
        "misago_users_slugs_search",
        table_name="misago_users",
        postgresql_ops={"slug": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.drop_index(
        "misago_users_moderators",
        table_name="misago_users",
        postgresql_where=sa.text("is_moderator = true"),
    )
    op.drop_index(
        "misago_users_inactive",
        table_name="misago_users",
        postgresql_where=sa.text("is_active = false"),
    )
    op.drop_index(
        "misago_users_full_names_search",
        table_name="misago_users",
        postgresql_ops={"full_name": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.drop_index(
        "misago_users_admins",
        table_name="misago_users",
        postgresql_where=sa.text("is_admin = true"),
    )
    op.drop_table("misago_users")
    # ### end Alembic commands ###
