"""add attachment types


Revision ID: 19d91a293d21
Revises: 135f742c6a0d
Create Date: 2022-07-09 12:47:18.856834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "19d91a293d21"
down_revision = "135f742c6a0d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "misago_attachment_types",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("extensions", sa.JSON(), nullable=False),
        sa.Column("mimetypes", sa.JSON(), nullable=False),
        sa.Column("size_limit", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("misago_attachment_types")
    # ### end Alembic commands ###
