"""attachment-types

Revision ID: 1044a3f45cb2
Revises: a5f43b2a479d
Create Date: 2022-07-10 21:39:47.018257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1044a3f45cb2"
down_revision = "a5f43b2a479d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "misago_attachment_types",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("extensions", sa.JSON(), nullable=False),
        sa.Column("mimetypes", sa.JSON(), nullable=False),
        sa.Column("size_limit", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("misago_attachment_types")
    # ### end Alembic commands ###
