"""moderators

Revision ID: 86a1f6e142b5
Revises: 1044a3f45cb2
Create Date: 2022-07-10 22:04:32.904832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "86a1f6e142b5"
down_revision = "1044a3f45cb2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "misago_moderators",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("category_id", sa.BigInteger(), nullable=False),
        sa.Column("group_id", sa.BigInteger(), nullable=True),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"], ["misago_categories.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["group_id"], ["misago_user_groups.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["misago_users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_constraint(
        "misago_user_group_memberships_group_id_fkey",
        "misago_user_group_memberships",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "misago_user_group_memberships",
        "misago_user_groups",
        ["group_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "misago_user_groups_role_key", "misago_user_groups", type_="unique"
    )
    op.drop_column("misago_user_groups", "role")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "misago_user_groups",
        sa.Column("role", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    )
    op.create_unique_constraint(
        "misago_user_groups_role_key", "misago_user_groups", ["role"]
    )
    op.drop_constraint(None, "misago_user_group_memberships", type_="foreignkey")
    op.create_foreign_key(
        "misago_user_group_memberships_group_id_fkey",
        "misago_user_group_memberships",
        "misago_user_groups",
        ["group_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.drop_table("misago_moderators")
    # ### end Alembic commands ###
