"""settings

Revision ID: ad2a1d098a41
Revises: e312cfb04cf7
Create Date: 2019-11-17 01:09:27.285062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ad2a1d098a41"
down_revision = "e312cfb04cf7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "misago_settings",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("python_type", sa.String(length=10), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("image_size", sa.Integer(), nullable=True),
        sa.Column("image_width", sa.Integer(), nullable=True),
        sa.Column("image_height", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("misago_settings")
    # ### end Alembic commands ###
