"""initial

Revision ID: f79fe2819be2
Revises: 
Create Date: 2019-10-27 04:37:04.504728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f79fe2819be2"
down_revision = None
branch_labels = ("misago",)
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "misago_categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "misago_settings",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "misago_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("slug", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=True),
        sa.Column("is_moderator", sa.Boolean(), nullable=False),
        sa.Column("joined_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "misago_threads",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("starter_id", sa.Integer(), nullable=True),
        sa.Column("starter_name", sa.String(length=255), nullable=False),
        sa.Column("last_poster_id", sa.Integer(), nullable=True),
        sa.Column("last_poster_name", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("last_posted_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["category_id"], ["misago_categories.id"]),
        sa.ForeignKeyConstraint(["last_poster_id"], ["misago_users.id"]),
        sa.ForeignKeyConstraint(["starter_id"], ["misago_users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_misago_threads_last_posted_at"),
        "misago_threads",
        ["last_posted_at"],
        unique=False,
    )
    op.create_table(
        "misago_posts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("thread_id", sa.Integer(), nullable=False),
        sa.Column("poster_id", sa.Integer(), nullable=True),
        sa.Column("poster_name", sa.String(length=255), nullable=False),
        sa.Column("body", sa.JSON(), nullable=False),
        sa.Column("posted_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["category_id"], ["misago_categories.id"]),
        sa.ForeignKeyConstraint(["poster_id"], ["misago_users.id"]),
        sa.ForeignKeyConstraint(["thread_id"], ["misago_threads.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("misago_posts")
    op.drop_index(op.f("ix_misago_threads_last_posted_at"), table_name="misago_threads")
    op.drop_table("misago_threads")
    op.drop_table("misago_users")
    op.drop_table("misago_settings")
    op.drop_table("misago_categories")
    # ### end Alembic commands ###
