# Generated by Django 4.2.10 on 2026-01-05 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("misago_threads", "0027_remove_post_edit_related_names"),
        ("misago_categories", "0014_rename_last_post_on_category_last_posted_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PostEdit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plugin_data", models.JSONField(default=dict)),
                ("user_name", models.CharField(max_length=255)),
                ("user_slug", models.CharField(max_length=255)),
                (
                    "edit_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("old_title", models.CharField(blank=True, max_length=255, null=True)),
                ("new_title", models.CharField(blank=True, max_length=255, null=True)),
                ("old_content", models.TextField(blank=True, null=True)),
                ("new_content", models.TextField(blank=True, null=True)),
                ("added_content", models.PositiveIntegerField(default=0)),
                ("removed_content", models.PositiveIntegerField(default=0)),
                ("attachments", models.JSONField(default=list)),
                ("added_attachments", models.PositiveIntegerField(default=0)),
                ("removed_attachments", models.PositiveIntegerField(default=0)),
                (
                    "hidden_by_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "hidden_by_slug",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_hidden", models.BooleanField(default=False)),
                ("edited_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("hidden_at", models.DateTimeField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="misago_categories.category",
                    ),
                ),
                (
                    "hidden_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="misago_threads.post",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="misago_threads.thread",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
