"""initial

Revision ID: 36a74db3b495
Revises: 
Create Date: 2019-10-27 04:38:10.504815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "36a74db3b495"
down_revision = None
branch_labels = ("testplugin",)
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "likes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("likes")
    # ### end Alembic commands ###
