# Generated by Django 2.2.3 on 2019-09-02 19:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

from ...cache.operations import StartCacheVersioning

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("misago_cache", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('title', models.CharField(max_length=150)),
                ('position', models.CharField(choices=[('top', 'Top navbar'), ('footer', 'Footer')], max_length=20)),
                ('relevance', models.PositiveSmallIntegerField(default=500, help_text='Relevance that the link has, used for ordering. (Max: 1000)', validators=[django.core.validators.MaxValueValidator(1000)])),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_modified_on', models.DateTimeField(blank=True, null=True)),
                ('last_modified_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-relevance',),
                'unique_together': {('link', 'position')},
            },
        ),
        StartCacheVersioning("menus")
    ]
