# Generated by Django 2.2.3 on 2019-09-11 07:13

from django.db import migrations, models
from ...cache.operations import StartCacheVersioning


class Migration(migrations.Migration):

    initial = True

    dependencies = [("misago_cache", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="MenuLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.URLField()),
                ("title", models.CharField(max_length=150)),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("top", "Header navbar"),
                            ("footer", "Footer"),
                            ("both", "Header and footer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("css_class", models.CharField(blank=True, max_length=255, null=True)),
                ("target", models.CharField(blank=True, max_length=100, null=True)),
                ("rel", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "ordering": ("order",),
                "get_latest_by": "order",
                "unique_together": {("link", "position")},
            },
        ),
        StartCacheVersioning("menus"),
    ]
