# Generated by Django 4.2.10 on 2024-09-10 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("misago_threads", "0014_plugin_data"),
        ("misago_categories", "0013_new_behaviors"),
        ("misago_attachments", "0002_move_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="misago_categories.category",
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="attachment",
            name="thread",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="misago_threads.thread",
            ),
        ),
    ]
