# Generated by Django 4.2.10 on 2025-01-06 13:04

from django.db import migrations, models

from ...core.utils import slugify


def populate_attachments_slugs(apps, _):
    Attachment = apps.get_model("misago_attachments", "Attachment")
    for attachment in Attachment.objects.order_by("id").iterator(chunk_size=50):
        attachment.slug = slugify(attachment.name)
        attachment.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("misago_attachments", "0003_attachment_populate_category_thread"),
    ]

    operations = [
        migrations.RunPython(
            populate_attachments_slugs,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="attachment",
            name="slug",
            field=models.CharField(max_length=255),
        ),
    ]
