# Generated by Django 4.2.10 on 2025-01-06 13:04
from PIL import Image

from django.db import migrations

from ..filetypes import filetypes


def populate_attachments_dimensions(apps, _):
    Attachment = apps.get_model("misago_attachments", "Attachment")

    queryset = Attachment.objects.filter(
        filetype_id__isnull=False,
        upload="",
    ).order_by("id")

    for attachment in queryset.iterator(chunk_size=50):
        filetype = filetypes.get_filetype(attachment.filetype_id)
        if not filetype.is_image or not attachment.upload:
            continue

        image = Image.open(attachment.upload.path)
        attachment.dimensions = "x".join(map(str, image.size))
        attachment.save(update_fields=["dimensions"])
        del image


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("misago_attachments", "0006_attachment_populate_thumbnail_size"),
    ]

    operations = [
        migrations.RunPython(
            populate_attachments_dimensions,
            migrations.RunPython.noop,
        ),
    ]
