# Generated by Django 4.2.10 on 2024-09-03 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("misago_notifications", "0003_indexes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="watchedthread",
            old_name="read_at",
            new_name="read_time",
        ),
    ]
