# Generated by Django 4.2.10 on 2025-08-10 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("misago_notifications", "0004_rename_read_at_watchedthread_read_time"),
    ]

    operations = [
        migrations.RunSQL(
            """
            UPDATE misago_notifications_notification
            SET verb = 'REPLIED_TO_THREAD'
            WHERE verb = 'REPLIED';
            """,
            """
            UPDATE misago_notifications_notification
            SET verb = 'REPLIED'
            WHERE verb = 'REPLIED_TO_THREAD';
            """,
        ),
        migrations.RunSQL(
            """
            UPDATE misago_notifications_notification
            SET verb = 'ADDED_TO_PRIVATE_THREAD'
            WHERE verb = 'INVITED';
            """,
            """
            UPDATE misago_notifications_notification
            SET verb = 'INVITED'
            WHERE verb = 'ADDED_TO_PRIVATE_THREAD';
            """,
        ),
    ]
