# Generated by Django 4.2.10 on 2025-09-02 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ("misago_notifications", "0005_rename_verbs"),
        ("misago_posts", "0002_move_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="misago_posts.post",
            ),
        ),
    ]
