# Generated by Django 4.2.10 on 2026-02-06 17:51

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("misago_notifications", "0005_rename_verbs"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchedthread",
            name="plugin_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AddIndex(
            model_name="watchedthread",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["plugin_data"], name="misago_noti_plugin__1fb246_gin"
            ),
        ),
    ]
