# Generated by Django 5.2.15 on 2026-09-29 21:44

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("misago_categories", "0016_remove_category_is_closed"),
        ("misago_threads", "0040_remove_post_search_document"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PostSearch",
            fields=[
                (
                    "post",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="misago_threads.post",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "thread_search_vector",
                    django.contrib.postgres.search.SearchVectorField(),
                ),
                (
                    "post_search_vector",
                    django.contrib.postgres.search.SearchVectorField(),
                ),
                ("posted_at", models.DateTimeField(db_index=True)),
                ("is_first_post", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="misago_categories.category",
                    ),
                ),
                (
                    "poster",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="misago_threads.thread",
                    ),
                ),
            ],
            options={
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["post_search_vector"],
                        name="misago_sear_post_se_3b77e2_gin",
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["thread_search_vector"],
                        name="misago_sear_thread__359afc_gin",
                    ),
                    models.Index(
                        condition=models.Q(("is_first_post", True)),
                        fields=["thread_id"],
                        name="search_post_search_is_firs_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SearchLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.CharField(db_index=True, max_length=45)),
                ("search_query", models.TextField()),
                (
                    "searched_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("is_public", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
                "indexes": [
                    models.Index(
                        condition=models.Q(("is_public", True)),
                        fields=["searched_at"],
                        name="search_log_public_searc_at_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ThreadSearch",
            fields=[
                (
                    "thread",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="misago_threads.thread",
                    ),
                ),
                ("title", models.TextField()),
                ("search_vector", django.contrib.postgres.search.SearchVectorField()),
                ("started_at", models.DateTimeField(db_index=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="misago_categories.category",
                    ),
                ),
                (
                    "starter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_vector"], name="misago_sear_search__1d8ef3_gin"
                    ),
                    models.Index(
                        condition=models.Q(("starter_id__isnull", False)),
                        fields=["starter_id"],
                        name="search_thread_search_start_idx",
                    ),
                ],
            },
        ),
    ]
