# Generated by Django 5.2.15 on 2026-08-11 19:43

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PostSearch",
            fields=[
                (
                    "post_id",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                ("category_id", models.PositiveIntegerField(db_index=True)),
                ("thread_id", models.PositiveIntegerField(db_index=True)),
                ("poster_id", models.PositiveIntegerField(null=True)),
                ("thread_title", models.TextField(null=True)),
                ("post_content", models.TextField()),
                ("search_vector", django.contrib.postgres.search.SearchVectorField()),
                ("posted_at", models.DateTimeField(db_index=True)),
                ("is_thread_pinned", models.BooleanField(default=False)),
                ("incoming_links", models.PositiveIntegerField(default=0)),
                ("is_hidden", models.BooleanField()),
                ("is_unapproved", models.BooleanField()),
            ],
            options={
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_vector"], name="misago_sear_search__4d0fbe_gin"
                    ),
                    models.Index(
                        condition=models.Q(("poster_id__isnull", False)),
                        fields=["poster_id"],
                        name="search_post_search_poster_idx",
                    ),
                ],
            },
        ),
    ]
