export const colors: Array<string> = [
  "#ff5630",
  "#36b37e",
  "#ffab00",
  "#00b8d9",
  "#6554c0",
  "#0065ff",
  "#ff7452",
  "#57d9a3",
  "#ffc400",
  "#00c7e6",
  "#8777d9",
  "#2684ff",
  "#de350b",
  "#00875a",
  "#ff991f",
  "#00a3bf",
  "#5243aa",
  "#0052cc",
]

export const icons: Array<string> = [
  "fas fa-pencil-ruler",
  "fas fa-rocket",
  "fas fa-heart",
  "fas fa-hammer",
  "fas fa-award",
  "fas fa-cog",
  "fas fa-adjust",
  "far fa-bookmark",
  "far fa-calendar",
  "fas fa-clinic-medical",
  "fas fa-coffee",
  "fas fa-car-battery",
  "far fa-compass",
  "far fa-envelope",
  "fas fa-flask",
  "far fa-image",
  "fas fa-paint-brush",
  "far fa-paper-plane",
  "fas fa-plane",
]

export const categoryBanner = {
  full: {
    align: "center",
    background: "#2c3e50",
    height: 100,
    url: "http://lorempixel.com/1280/200/",
  },
  half: {
    align: "center",
    background: "#2c3e50",
    height: 100,
    url: "http://lorempixel.com/768/200/",
  }
}

export const categories = [
  {
    id: "1",
    name: "EVE Information Portal",
    slug: "category",
    color: colors[0],
    icon: icons[0],
    banner: categoryBanner,
    threads: 16185,
    posts: 32584,
    isClosed: false,
    children: [
      {
        id: "2",
        name: "Dev Blogs",
        slug: "category",
        color: colors[6],
        icon: icons[6],
        banner: categoryBanner,
        threads: 16185,
        posts: 32584,
        isClosed: false,
        children: [],
        depth: 1,
        parent: null,
      },
      {
        id: "3",
        name: "Announcements",
        slug: "category",
        color: colors[7],
        icon: icons[7],
        banner: categoryBanner,
        threads: 16185,
        posts: 32584,
        isClosed: false,
        children: [],
        depth: 1,
        parent: null,
      },
      {
        id: "4",
        name: "Community Fittings",
        slug: "category",
        color: colors[8],
        icon: icons[8],
        banner: categoryBanner,
        threads: 16185,
        posts: 32584,
        isClosed: false,
        children: [],
        depth: 1,
        parent: null,
      },
    ],
    depth: 0,
    parent: null,
  },
  {
    id: "5",
    name: "New Citizens Q&A",
    slug: "category",
    color: colors[2],
    icon: icons[2],
    banner: categoryBanner,
    threads: 16185,
    posts: 32584,
    isClosed: false,
    children: [],
    depth: 0,
    parent: null,
  },
  {
    id: "6",
    name: "Communications Center",
    slug: "category",
    color: colors[3],
    icon: icons[3],
    banner: categoryBanner,
    threads: 16185,
    posts: 32584,
    isClosed: false,
    children: [
      {
        id: "7",
        name: "General discussion",
        slug: "category",
        color: colors[9],
        icon: icons[9],
        banner: categoryBanner,
        threads: 16185,
        posts: 32584,
        isClosed: false,
        children: [],
        depth: 1,
        parent: null,
      },
      {
        id: "8",
        name: "Crime & Punishment",
        slug: "category",
        color: colors[10],
        icon: icons[10],
        banner: categoryBanner,
        threads: 16185,
        posts: 32584,
        isClosed: false,
        children: [],
        depth: 1,
        parent: null,
      },
      {
        id: "9",
        name: "Out Of Pod Experience",
        slug: "category",
        color: colors[11],
        icon: icons[11],
        banner: categoryBanner,
        threads: 16185,
        posts: 32584,
        isClosed: false,
        children: [],
        depth: 1,
        parent: null,
      },
      {
        id: "10",
        name: "My EVE",
        slug: "category",
        color: colors[12],
        icon: icons[12],
        banner: categoryBanner,
        threads: 16185,
        posts: 32584,
        isClosed: false,
        children: [],
        depth: 1,
        parent: null,
      },
      {
        id: "11",
        name: "Skill Discussion",
        slug: "category",
        color: colors[13],
        icon: icons[13],
        banner: categoryBanner,
        threads: 16185,
        posts: 32584,
        isClosed: false,
        children: [],
        depth: 1,
        parent: null,
      },
    ],
    depth: 0,
    parent: null,
  },
  {
    id: "12",
    name: "Fiction Portal",
    slug: "category",
    color: colors[4],
    icon: icons[4],
    banner: categoryBanner,
    threads: 16185,
    posts: 32584,
    isClosed: false,
    children: [],
    depth: 0,
    parent: null,
  },
  {
    id: "13",
    name: "Events",
    slug: "category",
    color: colors[5],
    icon: icons[5],
    banner: categoryBanner,
    threads: 16185,
    posts: 32584,
    isClosed: false,
    children: [
      {
        id: "14",
        name: "In Game Events",
        slug: "category",
        color: colors[14],
        icon: icons[14],
        banner: categoryBanner,
        threads: 16185,
        posts: 32584,
        isClosed: false,
        children: [],
        depth: 1,
        parent: null,
      },
      {
        id: "15",
        name: "Out of Game Events",
        slug: "category",
        color: colors[15],
        icon: icons[15],
        banner: categoryBanner,
        threads: 16185,
        posts: 32584,
        isClosed: false,
        children: [],
        depth: 1,
        parent: null,
      },
    ],
    depth: 0,
    parent: null,
  },
]
