from django.conf.urls import patterns, url, include

urlpatterns = patterns('misago.users.views',
    url(r'^register/$', 'register.form', name="register"),
    url(r'^activate/(?P<username>[a-z0-9]+)-(?P<user>\d+)/(?P<token>[a-zA-Z0-9]+)/$', 'activation.activate', name="activate"),
    url(r'^resend-activation/$', 'activation.form', name="send_activation"),
    url(r'^reset-pass/$', 'password.form', name="forgot_password"),
    url(r'^reset-pass/(?P<username>[a-z0-9]+)-(?P<user>\d+)/(?P<token>[a-z0-9]+)/$', 'password.reset', name="reset_password"),
    url(r'^users/$', 'list.list', name="users"),
    url(r'^users/(?P<username>\w+)-(?P<user>\d+)/$', 'profiles.profile', name="user"),
    url(r'^users/(?P<username>\w+)-(?P<user>\d+)/threads/$', 'profiles.profile', name="user_threads", kwargs={'tab': 'threads'}),
    url(r'^users/(?P<username>\w+)-(?P<user>\d+)/following/$', 'profiles.profile', name="user_following", kwargs={'tab': 'following'}),
    url(r'^users/(?P<username>\w+)-(?P<user>\d+)/followiers/$', 'profiles.profile', name="user_followers", kwargs={'tab': 'followers'}),
    url(r'^users/(?P<username>\w+)-(?P<user>\d+)/details/$', 'profiles.profile', name="user_details", kwargs={'tab': 'details'}),
    url(r'^users/(?P<rank_slug>(\w|-)+)/$', 'list.list', name="users"),
    url(r'^usercp/$', 'usercp.options', name="usercp"),
    url(r'^usercp/credentials$', 'usercp.credentials', name="usercp_credentials"),
    url(r'^usercp/username$', 'usercp.username', name="usercp_username"),
    url(r'^usercp/avatar$', 'usercp.avatar', name="usercp_avatar"),
    url(r'^usercp/signature$', 'usercp.signature', name="usercp_signature"),
    url(r'^usercp/ignored$', 'usercp.ignored', name="usercp_ignored"),
)