# Generated by Django 4.2.10 on 2025-09-02 16:07

from django.conf import settings
import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("misago_categories", "0013_new_behaviors"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("misago_threads", "0021_remove_post_relations"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plugin_data", models.JSONField(default=dict)),
                ("poster_name", models.CharField(max_length=255)),
                ("original", models.TextField()),
                ("parsed", models.TextField()),
                ("metadata", models.JSONField(default=dict)),
                ("posted_at", models.DateTimeField(db_index=True)),
                ("updated_at", models.DateTimeField()),
                ("hidden_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("edits", models.PositiveIntegerField(default=0)),
                (
                    "last_editor_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "last_editor_slug",
                    models.SlugField(blank=True, max_length=255, null=True),
                ),
                (
                    "hidden_by_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "hidden_by_slug",
                    models.SlugField(blank=True, max_length=255, null=True),
                ),
                ("has_reports", models.BooleanField(default=False)),
                ("has_open_reports", models.BooleanField(default=False)),
                ("is_unapproved", models.BooleanField(db_index=True, default=False)),
                ("is_hidden", models.BooleanField(default=False)),
                ("is_protected", models.BooleanField(default=False)),
                ("search_document", models.TextField(blank=True, null=True)),
                ("search_vector", django.contrib.postgres.search.SearchVectorField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="misago_categories.category",
                    ),
                ),
                (
                    "hidden_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_editor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "poster",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="misago_threads.thread",
                    ),
                ),
            ],
            options={
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["plugin_data"], name="misago_post_plugin__09ef0a_gin"
                    ),
                    models.Index(
                        condition=models.Q(("has_open_reports", True)),
                        fields=["has_open_reports"],
                        name="misago_post_has_open_repo_part",
                    ),
                    models.Index(
                        condition=models.Q(("is_hidden", False)),
                        fields=["is_hidden"],
                        name="misago_post_is_hidden_part",
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_vector"], name="misago_post_search__25a5b5_gin"
                    ),
                    models.Index(
                        fields=["thread", "id"], name="misago_post_thread__b5961e_idx"
                    ),
                    models.Index(
                        fields=["poster", "posted_at"],
                        name="misago_post_poster__a3e25d_idx",
                    ),
                ],
            },
        ),
    ]
