# Generated by Django 4.2.10 on 2025-09-02 16:08

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ("misago_posts", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            """
            INSERT INTO misago_posts_post (
                id,
                category_id,
                thread_id,
                poster_id,
                poster_name,
                original,
                parsed,
                metadata,
                posted_at,
                updated_at,
                hidden_at,
                edits,
                last_editor_id,
                last_editor_name,
                last_editor_slug,
                hidden_by_id,
                hidden_by_name,
                hidden_by_slug,
                has_reports,
                has_open_reports,
                is_unapproved,
                is_hidden,
                is_protected,
                search_document,
                search_vector,
                plugin_data
            )
            SELECT
                id,
                category_id,
                thread_id,
                poster_id,
                poster_name,
                original,
                parsed,
                metadata::jsonb,
                posted_on,
                updated_on,
                hidden_on,
                edits,
                last_editor_id,
                last_editor_name,
                last_editor_slug,
                hidden_by_id,
                hidden_by_name,
                hidden_by_slug,
                has_reports,
                has_open_reports,
                is_unapproved,
                is_hidden,
                is_protected,
                search_document,
                search_vector,
                plugin_data::jsonb
            FROM misago_threads_post WHERE is_event = FALSE;
            """,
            migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            """
            SELECT SETVAL(
                'misago_posts_post_id_seq',
                (SELECT last_value FROM misago_threads_post_id_seq)
            );
            """,
            migrations.RunSQL.noop,
        ),
    ]
