from django.urls import path

from .views.list import category_threads, private_threads, threads
from .views.post import (
    ThreadPostLastView,
    ThreadPostSolutionView,
    ThreadPostUnapprovedView,
    ThreadPostUnreadView,
    ThreadPostView,
)
from .views.replies import private_thread_replies, thread_replies
from .views.threadupdates import (
    DeletePrivateThreadView,
    DeleteThreadUpdateView,
    HidePrivateThreadView,
    HideThreadUpdateView,
    UnhidePrivateThreadUpdateView,
    UnhideThreadUpdateView,
)


urlpatterns = [
    path(
        "threads/",
        threads,
        name="threads",
        kwargs={"is_index": False},
    ),
    path(
        "threads/<slug:filter>/",
        threads,
        name="threads",
    ),
    path(
        "c/<slug:slug>/<int:id>/",
        category_threads,
        name="category",
    ),
    path(
        "c/<slug:slug>/<int:id>/<slug:filter>/",
        category_threads,
        name="category",
    ),
    path(
        "private/",
        private_threads,
        name="private-threads",
    ),
    path(
        "private/<slug:filter>/",
        private_threads,
        name="private-threads",
    ),
    path(
        "t/<slug:slug>/<int:id>/",
        thread_replies,
        name="thread",
    ),
    path(
        "t/<slug:slug>/<int:id>/<int:page>/",
        thread_replies,
        name="thread",
    ),
    path(
        "p/<slug:slug>/<int:id>/",
        private_thread_replies,
        name="private-thread",
    ),
    path(
        "p/<slug:slug>/<int:id>/<int:page>/",
        private_thread_replies,
        name="private-thread",
    ),
    path(
        "t/<slug:slug>/<int:id>/post/<int:post_id>/",
        ThreadPostView.as_view(),
        name="thread-post",
    ),
    path(
        "t/<slug:slug>/<int:id>/last/",
        ThreadPostLastView.as_view(),
        name="thread-post-last",
    ),
    path(
        "t/<slug:slug>/<int:id>/unapproved/",
        ThreadPostUnapprovedView.as_view(),
        name="thread-post-unapproved",
    ),
    path(
        "t/<slug:slug>/<int:id>/unread/",
        ThreadPostUnreadView.as_view(),
        name="thread-post-unread",
    ),
    path(
        "t/<slug:slug>/<int:id>/solution/",
        ThreadPostSolutionView.as_view(),
        name="thread-post-solution",
    ),
    path(
        "t/<slug:slug>/<int:id>/hide-update/<int:thread_update>/",
        HideThreadUpdateView.as_view(),
        name="hide-thread-update",
    ),
    path(
        "p/<slug:slug>/<int:id>/hide-update/<int:thread_update>/",
        HidePrivateThreadView.as_view(),
        name="hide-private-thread-update",
    ),
    path(
        "t/<slug:slug>/<int:id>/unhide-update/<int:thread_update>/",
        UnhideThreadUpdateView.as_view(),
        name="unhide-thread-update",
    ),
    path(
        "p/<slug:slug>/<int:id>/unhide-update/<int:thread_update>/",
        UnhidePrivateThreadUpdateView.as_view(),
        name="unhide-private-thread-update",
    ),
    path(
        "t/<slug:slug>/<int:id>/delete-update/<int:thread_update>/",
        DeleteThreadUpdateView.as_view(),
        name="delete-thread-update",
    ),
    path(
        "p/<slug:slug>/<int:id>/delete-update/<int:thread_update>/",
        DeletePrivateThreadView.as_view(),
        name="delete-private-thread-update",
    ),
]
