from django.urls import path

from .views.edit import (
    edit_private_thread,
    edit_private_thread_post,
    edit_thread,
    edit_thread_post,
)
from .views.list import category_threads, private_threads, threads
from .views.redirect import (
    ThreadLastPostRedirectView,
    ThreadSolutionRedirectView,
    ThreadUnapprovedPostRedirectView,
    ThreadUnreadPostRedirectView,
)
from .views.replies import private_thread_replies, thread_replies
from .views.reply import reply_private_thread, reply_thread
from .views.selectcategory import SelectCategoryView
from .views.start import start_private_thread, start_thread
from .views.threadupdates import (
    DeletePrivateThreadView,
    DeleteThreadUpdateView,
    HidePrivateThreadView,
    HideThreadUpdateView,
    UnhidePrivateThreadUpdateView,
    UnhideThreadUpdateView,
)


urlpatterns = [
    path(
        "start-thread/",
        SelectCategoryView.as_view(),
        name="start-thread",
    ),
    path(
        "c/<slug:slug>/<int:id>/start-thread/",
        start_thread,
        name="start-thread",
    ),
    path(
        "private/start-thread/",
        start_private_thread,
        name="start-private-thread",
    ),
    path(
        "threads/",
        threads,
        name="threads",
        kwargs={"is_index": False},
    ),
    path(
        "threads/<slug:filter>/",
        threads,
        name="threads",
    ),
    path(
        "c/<slug:slug>/<int:id>/",
        category_threads,
        name="category",
    ),
    path(
        "c/<slug:slug>/<int:id>/<slug:filter>/",
        category_threads,
        name="category",
    ),
    path(
        "private/",
        private_threads,
        name="private-threads",
    ),
    path(
        "private/<slug:filter>/",
        private_threads,
        name="private-threads",
    ),
    path(
        "t/<slug:slug>/<int:id>/",
        thread_replies,
        name="thread",
    ),
    path(
        "t/<slug:slug>/<int:id>/<int:page>/",
        thread_replies,
        name="thread",
    ),
    path(
        "p/<slug:slug>/<int:id>/",
        private_thread_replies,
        name="private-thread",
    ),
    path(
        "p/<slug:slug>/<int:id>/<int:page>/",
        private_thread_replies,
        name="private-thread",
    ),
    path(
        "t/<slug:slug>/<int:id>/last/",
        ThreadLastPostRedirectView.as_view(),
        name="thread-last-post",
    ),
    path(
        "t/<slug:slug>/<int:id>/unread/",
        ThreadUnreadPostRedirectView.as_view(),
        name="thread-unread-post",
    ),
    path(
        "t/<slug:slug>/<int:id>/unapproved/",
        ThreadUnapprovedPostRedirectView.as_view(),
        name="thread-unapproved-post",
    ),
    path(
        "t/<slug:slug>/<int:id>/solution/",
        ThreadSolutionRedirectView.as_view(),
        name="thread-solution-post",
    ),
    path(
        "t/<slug:slug>/<int:id>/reply/",
        reply_thread,
        name="reply-thread",
    ),
    path(
        "p/<slug:slug>/<int:id>/reply/",
        reply_private_thread,
        name="reply-private-thread",
    ),
    path(
        "t/<slug:slug>/<int:id>/edit/",
        edit_thread,
        name="edit-thread",
    ),
    path(
        "p/<slug:slug>/<int:id>/edit/",
        edit_private_thread,
        name="edit-private-thread",
    ),
    path(
        "t/<slug:slug>/<int:id>/edit/<int:post>/",
        edit_thread_post,
        name="edit-thread",
    ),
    path(
        "p/<slug:slug>/<int:id>/edit/<int:post>/",
        edit_private_thread_post,
        name="edit-private-thread",
    ),
    path(
        "t/<slug:slug>/<int:id>/hide-update/<int:thread_update>/",
        HideThreadUpdateView.as_view(),
        name="hide-thread-update",
    ),
    path(
        "p/<slug:slug>/<int:id>/hide-update/<int:thread_update>/",
        HidePrivateThreadView.as_view(),
        name="hide-private-thread-update",
    ),
    path(
        "t/<slug:slug>/<int:id>/unhide-update/<int:thread_update>/",
        UnhideThreadUpdateView.as_view(),
        name="unhide-thread-update",
    ),
    path(
        "p/<slug:slug>/<int:id>/unhide-update/<int:thread_update>/",
        UnhidePrivateThreadUpdateView.as_view(),
        name="unhide-private-thread-update",
    ),
    path(
        "t/<slug:slug>/<int:id>/delete-update/<int:thread_update>/",
        DeleteThreadUpdateView.as_view(),
        name="delete-thread-update",
    ),
    path(
        "p/<slug:slug>/<int:id>/delete-update/<int:thread_update>/",
        DeletePrivateThreadView.as_view(),
        name="delete-private-thread-update",
    ),
]
